export const productData = {
  products: [
    // {
    //   id: "",
    //   availibility: "",
    //   productData: {
    //     categoty: "",
    //     type: "",
    //     price: "",
    //     discountPrice: "",
    //     about: "",
    //     availibleColor: "",
    //     availableSize: "",
    //     minimumQuantity: "",
    //     inStock: "",
    //   },
    //   productImages :{
    //     mainImage:"",
    //     quickView:"",
    //     subImages:[{}]
    //   }
    // },
    {
      id: 1,
      inStock:150,
      vendor: "alpha seller",
      category: "Men Wear",
      link: "furniture-home",
      type: "Casual Shirt",
      minItem: "5",
      title: "Outdoor wooden bridge ",
      discountPrice: 190,
      price:380,
      color: true,
      size : true,
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      images: [
        {
          id: 1,
          image: require("./productImages/image.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp1.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp1.jpg"),
        },
      ],
      image: require("./productImages/image.jpg"),
      imageHover: require("./productImages/image.jpg"),
      quickView: require("./productImages/image.jpg"),
    },
    {
      id: 2,
      inStock:190,
      vendor: "near seller",
      category: "Shoes",
      link: "pet-supplies",
      type: "Sneakers",
      minItem: "8",
      title: "Bathroom clamp board ",
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
        discountPrice: 790,
        price:1080,
      color: false,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/exp2.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp2.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp2.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp2.jpg"),
        },
      ],
      image: require("./productImages/exp2.jpg"),
      imageHover: require("./productImages/exp2.jpg"),
      quickView: require("./productImages/exp2.jpg"),
    },
    {
      id: 3,
      inStock:250,
      vendor: "saloon seller",
      category: "Unisex Shoes",
      link: "garden-outdoor",
      type: "Sports Shoes",
      minItem: "5",
      title: "Digital watch with bluetooth and wifi inbuild",
      discountPrice: 100,
      price:250,
      color: true,
      images: [
        {
          id: 1,
          image: require("./productImages/exp3.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp3.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp3.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp3.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp3.jpg"),
      imageHover: require("./productImages/exp3.jpg"),
      quickView: require("./productImages/exp3.jpg"),
    },
    {
      id: 4,
      inStock:320,
      vendor: "tokyo seller",
      category: "",
      link: "pet-supplies",
      type: "",
      minItem: "12",
      title: "Outdoor Indoor Lantern",
      discountPrice: 250,
      price:500,
      color: true,
      images: [
        {
          id: 1,
          image: require("./productImages/image20.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image20.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image20.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image20.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image20.jpg"),
      imageHover: require("./productImages/image20.jpg"),
      quickView: require("./productImages/image20.jpg"),
    },
    {
      id: 5,
      inStock:480,
      vendor: "de costa seller",
      category: "",
      link: "kitchen-dining",
      type: "",
      minItem: "21",
      title: "Men's shirt blue",
      discountPrice: 180,
      price:760,
      color: false,
      size : true,
      images: [
        {
          id: 1,
          image: require("./productImages/exp5.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp5.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp5.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp5.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp5.jpg"),
      imageHover: require("./productImages/exp5.jpg"),
      quickView: require("./productImages/exp5.jpg"),
    },
    {
      id: 6,
      inStock:670,
      vendor: "parefine seller",
      category: "",
      link: "craft-hobbies",
      type: "",
      minItem: "16",
      title: "Standing Lamp home decor Good use ",
      discountPrice: 280,
      price:500,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/exp6.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp6.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp6.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp6.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp6.jpg"),
      imageHover: require("./productImages/exp6.jpg"),
      quickView: require("./productImages/exp6.jpg"),
    },
    {
      id: 7,
      inStock:350,
      vendor: "deigo seller",
      category: "",
      link: "bedroom-bathroom",
      type: "",
      minItem: "19",
      title: "Home decoration Stuff ",
      discountPrice: 120,
      price:380,
      color: false,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp7.jpg"),
        },
      ],
      image: require("./productImages/exp7.jpg"),
      imageHover: require("./productImages/exp7.jpg"),
      quickView: require("./productImages/exp7.jpg"),
    },
    {
      id: 8,
      inStock:50,
      vendor: "benzo seller",
      category: "",
      link: "kids-section",
      type: "",
      minItem: "22",
      title: "Home decor lightings indoor and outdoor use ",
      discountPrice: 120,
      price:420,
      images: [
        {
          id: 1,
          image: require("./productImages/exp8.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp8.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp8.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp8.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp8.jpg"),
      imageHover: require("./productImages/exp8.jpg"),
      quickView: require("./productImages/exp8.jpg"),
    },
    {
      id: 9,
      inStock:850,
      vendor: "costica seller",
      category: "",
      link: "birthstone",
      type: "",
      minItem: "28",
      title: "Home table  ",
      discountPrice: 430,
      price:600,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/image21.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image21.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image21.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image21.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image21.jpg"),
      imageHover: require("./productImages/image21.jpg"),
      quickView: require("./productImages/image21.jpg"),
    },
    {
      id: 10,
      inStock:150,
      vendor: "espaniol seller",
      category: "",
      link: "children",
      type: "",
      minItem: "12",
      title: "Green indoor plant",
      discountPrice: 620,
      price:720,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/image24.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image24.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image24.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image24.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image24.jpg"),
      imageHover: require("./productImages/image24.jpg"),
      quickView: require("./productImages/image24.jpg"),
    },
    {
      id: 11,
      inStock:250,
      vendor: "enrique seller",
      category: "",
      link: "",
      type: "jewelry-boxes",
      minItem: "14",
      title: "Gaming Chair black color with hand, neckrest",
      discountPrice: 190,
      price:380,
      color: true,
      size : true,
      images: [
        {
          id: 1,
          image: require("./productImages/image26.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image26.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image26.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image26.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image26.jpg"),
      imageHover: require("./productImages/image26.jpg"),
      quickView: require("./productImages/image26.jpg"),
    },
    {
      id: 12,
      inStock:830,
      vendor: "gamma seller",
      category: "",
      type: "",
      link: "wedding-rings",
      minItem: "16",
      title: "Belted chino trousers polo",
      discountPrice: 180,
      price:480,
      color: true,
      size : true,
      images: [
        {
          id: 1,
          image: require("./productImages/exp4.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp4.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp4.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp4.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp4.jpg"),
      imageHover: require("./productImages/exp4.jpg"),
      quickView: require("./productImages/exp4.jpg"),
    },
    {
      id: 13,
      inStock:450,
      vendor: "virutoso seller",
      category: "",
      link: "kids-watches",
      type: "",
      minItem: "22",
      title: "Belted chino trousers polo ",
      price: 120,
      discountPrice:80,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/exp1.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp1.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp1.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp1.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp1.jpg"),
      imageHover: require("./productImages/exp1.jpg"),
      quickView: require("./productImages/exp1.jpg"),
    },
    {
      id: 14,
      inStock:210,
      vendor: "forcaster seller",
      category: "",
      link: "mens-watches",
      type: "",
      minItem: "11",
      title: "Belted chino trousers polo",
      price: 540,
      discountPrice:240,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/exp7.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/exp7.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/exp7.jpg"),
      imageHover: require("./productImages/exp7.jpg"),
      quickView: require("./productImages/exp7.jpg"),
    },
    {
      id: 15,
      inStock:190,
      vendor: "sigmasion seller",
      category: "",
      link:"furniture-home",
      type: "",
      minItem: "8",
      title: "Ceiling fan , four blade with lights ",
      discountPrice: 60,
      price:280,
      color: true,
      size : true,
      images: [
        {
          id: 1,
          image: require("./productImages/image32.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image32.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image32.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image32.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image32.jpg"),
      imageHover: require("./productImages/image32.jpg"),
      quickView: require("./productImages/image32.jpg"),
    },
    {
      id: 16,
      inStock:230,
      vendor: "sigmasion seller",
      category: "",
      link:"craft-hobbies",
      type: "",
      minItem: "6",
      title: "Empty boxes 8 boxes ",
      discountPrice: 60,
      price:280,
      color: true,
      size : true,
      images: [
        {
          id: 1,
          image: require("./productImages/image40.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image40.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image40.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image40.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image40.jpg"),
      imageHover: require("./productImages/image40.jpg"),
      quickView: require("./productImages/image40.jpg"),
    },
    {
      id: 17,
      inStock:280,
      vendor: "sigmasion seller",
      category: "",
      link:"bedroom-bathroom",
      type: "",
      minItem: "3",
      title: " Some Kitchen stuff ",
      discountPrice: 60,
      price:280,
      color: true,
      size : false,
      images: [
        {
          id: 1,
          image: require("./productImages/image41.jpg"),
        },
        {
          id: 2,
          image: require("./productImages/image41.jpg"),
        },
        {
          id: 3,
          image: require("./productImages/image41.jpg"),
        },
        {
          id: 4,
          image: require("./productImages/image41.jpg"),
        },
      ],
      about:
        "about the product data Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.",
      image: require("./productImages/image41.jpg"),
      imageHover: require("./productImages/image41.jpg"),
      quickView: require("./productImages/image41.jpg"),
    }
  ],
  addedItems: [],
  addedItemsToCompare: [],
  total: 0,
  shipping: 0,
};
